# Generated by Django 2.0.7 on 2020-11-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0006_auto_20190427_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='uconsumed',
            field=models.IntegerField(default=0, max_length=11, verbose_name='已消费金额'),
        ),
    ]
