# Generated by Django 2.0.7 on 2020-11-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0007_userinfo_uconsumed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uemail',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
    ]
