# Generated by Django 2.0.7 on 2020-11-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0010_goodscomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ulotterycount',
            field=models.IntegerField(default=0, verbose_name='用户剩余抽奖次数'),
        ),
    ]
